#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/NetworkMonitorPayment
dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release --self-contained true -p:PublishSingleFile=true
